lang.STR = {
	"loading_title": "Prévention des Acanthasters en Nouvelle-Calédonie",
	"loading_desc":"Een remplissant ce formulaire vous nous aidez à protéger les récifs de Nouvelle-Calédonie.",
	"add_item_title":" Signaler des Acantasthers",	
	"observer_name":"Observateur *",
	"observer_name.placeholder":"Nom de l'observateur",
	"observer_tel.placeholder":"Numéro de téléphone de l'observateur",
	"observer_mail.placeholder":"Adresse mail de l'observateur",
	"observation_date":"Date de l'observation *",
	"observation_date.placeholder":"Date de l'observation",
	"observation_location.placeholder":"Informations complémentaires position",
	"observation_localisation":"Sélectionner la position *",
	"observation_region.placeholder":"Région",
	"observation_country.placeholder":"Pays",
	"observation_latitude.placeholder":"Latitude",
	"observation_longitude.placeholder":"Longitude",
	"observation_number":"Nombre d'acanthasters",
	"observation_number.placeholder":"Nombre d'acanthasters observées",
	"observation_culled.placeholder":"Nombre d'acanthasters nettoyées (si nettoyage)",
	"observation_method":"Méthode d'observation *",
	"observation_1method.value":"snorkelling",
	"observation_2method.value":"scuba diving",
	"observation_1method":"PMT",
	"observation_2method":"Plongée bouteille",
	"depth_range":"Tranche de profondeur *",
	"depth_1range.value":"shallow",
	"depth_1range":"Moins de 2m",
	"depth_2range.value":"medium",
	"depth_2range":"Entre 2 et 10m",
	"depth_3range.value":"deep",
	"depth_3range":"Plus de 10m",
	"counting_method_title":"Méthode de comptage",
	"counting_method_desc.title":"Merci d'indiquer la méthode utilisée : 'nage minutée', si vous avez nagé un certain temps, 'distance parcourue' si vous avez nagé une certaine distance, ou une autre méthode",
	"timed_swim.placeholder":"Temps de nage",
	"distance_swim.placeholder":"Distance parcourue",
	"other_swim.placeholder":"Autre",
	"remarks":"Remarques",
	"remarks.placeholder":"Ex: couverture de corail vivant, coraux morts, blanchiment, présence d'algues…",
	"observation_state":"Impact des acanthasters",
	"observation_1state":"Faible ou à confirmer",
	"observation_1state.value":"Low",
	"observation_2state":"Moyen",
	"observation_2state.value":"Medium",
	"observation_3state":"Elevé",
	"observation_3state.value":"Hight",
	"recaptcha":"Captcha",
	"submit":"ENVOYER",
	"or":"ou",
	"cancel":"X",
	"cancel.title":"Annuler"
};
